<?php
namespace frontend\widgets\homepage;
use yii\base\Widget;

/**
 * Created by PhpStorm.
 * User: CX
 * Date: 2018/3/14
 * Time: 23:23
 */

class SliderWidget extends Widget
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        parent::run(); // TODO: Change the autogenerated stub
        return $this->render('slider_layout');
    }
}