<?php
/**
 * Created by PhpStorm.
 * User: CX
 * Date: 2018/3/18
 * Time: 10:51
 */
namespace backend\modules\System;

class Module extends \yii\base\Module
{
    public $controllerNamespace = 'backend\modules\System\controllers';

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->modules = [
            'setting' => 'backend\modules\System\modules\Setting\Module',
            'tourists' => 'backend\modules\System\modules\Tourists\Module',
        ];
    }

}