<?php
/**
 * Created by PhpStorm.
 * User: CX
 * Date: 2018/3/15
 * Time: 10:38
 */

namespace frontend\modules\Search;


class Module extends \yii\base\Module
{
    public $controllerNamespace = 'frontend\modules\Search\controllers';

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }
}