<?php
/**
 * Created by PhpStorm.
 * User: CX
 * Date: 2018/3/17
 * Time: 21:30
 */
namespace backend\modules\News;

class Module extends \yii\base\Module
{
    /**
     * @inheritdoc
     */
    public $controllerNamespace = 'backend\modules\News\controllers';

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }
}