<?php
/**
 * Created by PhpStorm.
 * User: CX
 * Date: 2018/3/17
 * Time: 23:38
 */

namespace backend\themes\hui;


use yii\web\AssetBundle;
use yii\web\View;

class UeditorAsset extends AssetBundle
{
    public $js = [
        "lib/ueditor/1.4.3/ueditor.config.js",
        "lib/ueditor/1.4.3/ueditor.all.min.js",
        "lib/ueditor/1.4.3/lang/zh-cn/zh-cn.js",
    ];

    public $jsOptions = [
        'position' => View::POS_HEAD,
    ];

    public $css = [
    ];

    public function init()
    {
        $this->sourcePath = '@app/themes/' . BREST_BACKEND_THEME_HUI . '/assets';
        parent::init(); // TODO: Change the autogenerated stub
    }
}