<?php
/**
 * Created by PhpStorm.
 * User: CX
 * Date: 2018/3/16
 * Time: 11:32
 */
namespace backend\modules\Product\modules\Category;

class Module extends \yii\base\Module
{

    public $controllerNamespace = 'backend\modules\Product\modules\Category\controllers';

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }
}