<?php
/**
 * Created by PhpStorm.
 * User: CX
 * Date: 2018/3/18
 * Time: 10:51
 */
namespace backend\modules\Statistics;

class Module extends \yii\base\Module
{
    public $controllerNamespace = 'backend\modules\Statistics\controllers';

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->modules = [
            'ips' => 'backend\modules\Statistics\modules\Ips\Module',
            'forms' => 'backend\modules\Statistics\modules\Forms\Module',
        ];
    }

}